### ISSUE TITLE
OpenApiDriver has compatibility issues with Robot Framework 7.0.0

### ISSUE THREAD

**Issue by SaaristoAntti** [MarketSquare/robotframework-openapidriver#37] opened 2024-01-20 13:37 UTC
Hi, 

Really nice library! I was playing around and noticed that OpenApiDriver doesn't work with RF 7.0.0.
Reproduce steps:
1) git clone https://github.com/MarketSquare/robotframework-openapidriver.git
2) poetry install
3) on console 1 start test server
> poetry run inv start-api

4) on console 2 run tests with RF 6.1
> poetry run inv atests # 92 tests, 80 passed, 0 failed, 12 skipped

5) upgrade to RF 7.0.0
> poetry add robotframework==7.0.0 

6) run tests
> poetry run inv atests 

=> 92 tests, 7 passed, 85 failed

**Comment by robinmackaij** [comment] 2024-01-20 13:52
Hi @SaaristoAntti,

There was indeed an unforseen regression that I didn't catch (OpenApiLibCore was checked and is fine, OpenApiDriver slipped through and is impacted).

This issue is due to an unforseen change in RF 7.0 that changes `BuildIn.run_keyword` in very specific circumstances . These specific circumstances are true for one keyword call in OpenApiDriver.

Pekka intends to include a fix for this regression in RF 7.0.1.

Please let me know if you urgently need support for RF 7 with OpenApiDriver or that it's fine for you to wait for RF 7.0.1. A fix from my side would have to be a (somewhat dirty) workaround to prevent running the issue and definitely not code that I would want to keep in place after the fix rolls out.

**Comment by SaaristoAntti** [comment] 2024-01-20 14:51
Hi,

wow that was fast reply. No need for urgent fix and I wouldn't even recommend to do any dirty fixes.(I have seen too many quick and dirty fixes :). I was just playing around with the library since I find it very interesting and useful on API testing. Keep up the good work in the Robot Framework environment!

**Comment by robinmackaij** [comment] 2024-01-20 15:02
The related issue in the robotframework repo is this one:
https://github.com/robotframework/robotframework/issues/5031

I'll keep this issue open until a fix is available. Feel free to contact me (easiest is on the RF Slack) if you have questions!

**Comment by robinmackaij** [comment] 2024-07-02 07:03
Resolved with the release of RF 7.0.1.

**Closed as completed by robinmackaij** 2024-07-02 07:03 UTC
